"""
SignalIQ — Agent Entry Point

This is the main entry point that wires together the full Vision Agents
pipeline. Following the official Vision Agents pattern:
  - AgentLauncher creates the Agent
  - Runner manages the lifecycle
  - Agent orchestrates all components via native SDK integrations

Run with:
  uv run agent/main.py serve
  # or
  python agent/main.py serve
"""

import logging
import os
import sys

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv

load_dotenv()

from agent.config import config
from agent.llm.prompt_templates import SIGNALIQ_SYSTEM_PROMPT

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(message)s")


async def create_agent(**kwargs):
    """
    Factory function called by Vision Agents to create the SignalIQ agent.

    This wires together ALL Vision Agents native integrations:
    - getstream.Edge() → Stream's <30ms latency edge network
    - gemini.Realtime(fps=1) → Native Gemini Live for real-time reasoning
    - elevenlabs.TTS() → Native ElevenLabs TTS for whisper delivery
    - deepgram.STT() → Native Deepgram STT for speech transcription
    - ultralytics.YOLOPoseProcessor → YOLO pose/face detection
    - SignalIQProcessor → Custom FER + engagement scoring (our showpiece)
    """
    from vision_agents.core import Agent, User
    from vision_agents.plugins import getstream, gemini, elevenlabs, deepgram, ultralytics

    from agent.vision.frame_processor import SignalIQProcessor

    logger.info("Creating SignalIQ agent...")

    agent = Agent(
        # ── Stream Edge Network ──────────────────────────
        # <500ms join time, <30ms audio/video latency
        edge=getstream.Edge(),

        # ── Agent Identity ───────────────────────────────
        agent_user=User(
            name=config.agent_name,
            id=config.agent_id,
        ),

        # ── System Prompt ────────────────────────────────
        # The prompt IS the product quality
        instructions=SIGNALIQ_SYSTEM_PROMPT,

        # ── Gemini Live (Real-Time LLM Reasoning) ───────
        # 1fps to Gemini — cost-efficient; YOLO/FER runs at 10fps locally
        # Gemini sees: annotated frames + SignalIQEvent metadata + STT transcript
        llm=gemini.Realtime(
            model=config.llm.gemini_model,
            fps=config.llm.gemini_fps,
        ),

        # ── ElevenLabs TTS (Whisper Delivery) ────────────
        # Calm, low-volume voice optimized for coaching whispers
        tts=elevenlabs.TTS(
            voice_id=config.audio.tts_voice_id,
            model_id=config.audio.tts_model_id,
        ),

        # ── Deepgram STT (Speech Transcription) ─────────
        # Transcribes both rep and prospect speech in real-time
        # Used to correlate emotional reactions with specific words/topics
        stt=deepgram.STT(
            model=config.audio.stt_model,
            language=config.audio.stt_language,
        ),

        # ── Video Processors ────────────────────────────
        processors=[
            # Custom FER + engagement scoring (10fps, runs locally)
            SignalIQProcessor(fps=config.vision.processor_fps),

            # YOLO pose detection (body pose + face landmarks)
            ultralytics.YOLOPoseProcessor(
                model_path=config.vision.yolo_model_path,
                conf_threshold=config.vision.yolo_confidence_threshold,
            ),
        ],
    )

    logger.info("SignalIQ agent created successfully")
    return agent


async def join_call(agent, call_type: str, call_id: str, **kwargs):
    """
    Called when the agent should join a video call.

    This is the Vision Agents lifecycle pattern:
    1. Upsert agent user (Stream requires it for server-side auth)
    2. Create a call reference
    3. Join the call
    4. Agent processes frames and generates whispers automatically
    5. Agent finishes when the call ends
    """
    logger.info(f"SignalIQ joining call: {call_type}/{call_id}")

    # Ensure the agent user exists in Stream before creating a call.
    # Stream server-side auth requires created_by_id to reference a valid user.
    try:
        stream_client = agent.edge._client  # Access the underlying Stream client
        stream_client.upsert_users(
            {
                "id": config.agent_id,
                "name": config.agent_name,
                "role": "admin",
            }
        )
        logger.info(f"Upserted agent user: {config.agent_id}")
    except Exception as e:
        logger.warning(f"Could not upsert agent user (may already exist): {e}")

    call = await agent.create_call(call_type, call_id)

    async with agent.join(call):
        logger.info("SignalIQ is live — analyzing prospect signals...")
        # The agent runs continuously until the call ends.
        # Frame processing happens via SignalIQProcessor.
        # Whispers are generated by Gemini and delivered via ElevenLabs.
        await agent.finish()

    logger.info(f"SignalIQ finished call: {call_id}")


def main():
    """
    Entry point — uses Vision Agents Runner for lifecycle management.

    Supports:
    - `python agent/main.py serve` — HTTP server mode
    - `python agent/main.py join <call_type> <call_id>` — Direct join mode
    """
    from vision_agents.core import AgentLauncher, Runner

    logger.info("Starting SignalIQ...")
    logger.info(f"  Agent: {config.agent_name} ({config.agent_id})")
    logger.info(f"  Gemini: {config.llm.gemini_model} @ {config.llm.gemini_fps}fps")
    logger.info(f"  Processor: SignalIQProcessor @ {config.vision.processor_fps}fps")
    logger.info(f"  YOLO: {config.vision.yolo_model_path}")

    runner = Runner(
        AgentLauncher(
            create_agent=create_agent,
            join_call=join_call,
        )
    )
    runner.cli()


if __name__ == "__main__":
    main()
